root: true
ignorePatterns: ["!.*", "dist", "node_modules"]
parser: "@typescript-eslint/parser"
extends:
  - plugin:astro/recommended
overrides:
  - files:
      - "*.astro"
    parser: astro-eslint-parser
    parserOptions:
      parser: "@typescript-eslint/parser"
      extraFileExtensions:
        - ".astro"
